// Car Data for car.livechennai.com - Auto-generated with verified local images
// Generated on: 2026-06-08T11:32:35.920Z

const brandsData = [
    { name: "Maruti Suzuki", logo: "assets/images/brands/maruti.png" },
    { name: "Hyundai", logo: "assets/images/brands/hyundai.png" },
    { name: "Tata", logo: "assets/images/brands/tata.png" },
    { name: "Mahindra", logo: "assets/images/brands/mahindra.png" },
    { name: "Toyota", logo: "assets/images/brands/toyota.png" },
    { name: "Honda", logo: "assets/images/brands/honda.png" },
    { name: "Kia", logo: "assets/images/brands/kia.png" },
    { name: "MG", logo: "assets/images/brands/mg.png" },
    { name: "Skoda", logo: "assets/images/brands/skoda.png" },
    { name: "Volkswagen", logo: "assets/images/brands/vw.png" },
    { name: "BMW", logo: "assets/images/brands/bmw.png" },
    { name: "Audi", logo: "assets/images/brands/audi.png" },
    { name: "Mercedes-Benz", logo: "assets/images/brands/benz.png" }
];

const modelsData = {
    "Maruti Suzuki": ["Swift"],
    "Hyundai": ["Creta"],
    "Tata": ["Nexon"],
    "Mahindra": ["XUV700"],
    "Toyota": ["Fortuner"],
    "Honda": ["City"],
    "Kia": ["Seltos"],
    "MG": ["Hector"],
    "Skoda": ["Slavia"],
    "Volkswagen": ["Virtus"],
    "BMW": ["3 Series Gran Limousine"],
    "Audi": ["A4"],
    "Mercedes-Benz": ["C-Class"]
};

function formatNumber(num) {
    return num.toLocaleString('en-IN');
}

const carsData = [
    {
        id: 1,
        brand: "Maruti Suzuki",
        model: "Swift",
        year: 2024,
        variant: "ZXi+",
        price: 899000,
        formatted_price: "₹8,99,000",
        emi: "₹18,500",
        fuel_type: "Petrol",
        transmission: "Manual",
        mileage: "24.8 kmpl",
        engine: "1197 cc",
        seating_capacity: "5 Seater",
        body_type: "Hatchback",
        images: [
            "assets/images/swift/1.jpg",
            "assets/images/swift/2.jpg",
            "assets/images/swift/3.jpg",
            "assets/images/swift/4.jpg",
            "assets/images/swift/5.jpg"
        ],
        source_link: "https://www.marutisuzuki.com/swift",
        featured: true
    },
    {
        id: 2,
        brand: "Hyundai",
        model: "Creta",
        year: 2024,
        variant: "SX(O) 1.5 Diesel AT",
        price: 1999000,
        formatted_price: "₹19,99,000",
        emi: "₹38,500",
        fuel_type: "Diesel",
        transmission: "Automatic",
        mileage: "19.1 kmpl",
        engine: "1493 cc",
        seating_capacity: "5 Seater",
        body_type: "SUV",
        images: [
            "assets/images/creta/1.png",
            "assets/images/creta/2.png",
            "assets/images/creta/3.jpg",
            "assets/images/creta/4.jpg",
            "assets/images/creta/5.png"
        ],
        source_link: "https://www.hyundai.com/in/en/find-a-car/creta/highlights",
        featured: true
    },
    {
        id: 3,
        brand: "Tata",
        model: "Nexon",
        year: 2024,
        variant: "Fearless+ S Diesel AMT",
        price: 1549000,
        formatted_price: "₹15,49,000",
        emi: "₹31,000",
        fuel_type: "Diesel",
        transmission: "Automatic",
        mileage: "24.08 kmpl",
        engine: "1497 cc",
        seating_capacity: "5 Seater",
        body_type: "SUV",
        images: [
            "assets/images/nexon/1.jpg",
            "assets/images/nexon/2.jpg",
            "assets/images/nexon/3.jpg",
            "assets/images/nexon/4.jpg",
            "assets/images/nexon/5.jpg"
        ],
        source_link: "https://cars.tatamotors.com/suv/nexon",
        featured: false
    },
    {
        id: 4,
        brand: "Mahindra",
        model: "XUV700",
        year: 2024,
        variant: "AX7 L Diesel AT AWD",
        price: 2699000,
        formatted_price: "₹26,99,000",
        emi: "₹53,000",
        fuel_type: "Diesel",
        transmission: "Automatic",
        mileage: "16.0 kmpl",
        engine: "2184 cc",
        seating_capacity: "7 Seater",
        body_type: "SUV",
        images: [
            "assets/images/xuv700/1.png",
            "assets/images/xuv700/2.png",
            "assets/images/xuv700/3.png",
            "assets/images/xuv700/4.png",
            "assets/images/xuv700/5.png"
        ],
        source_link: "https://auto.mahindra.com/suv/xuv700",
        featured: true
    },
    {
        id: 5,
        brand: "Toyota",
        model: "Fortuner",
        year: 2024,
        variant: "GR-S 2.8 Diesel 4x4 AT",
        price: 5144000,
        formatted_price: "₹51,44,000",
        emi: "₹95,000",
        fuel_type: "Diesel",
        transmission: "Automatic",
        mileage: "10.0 kmpl",
        engine: "2755 cc",
        seating_capacity: "7 Seater",
        body_type: "SUV",
        images: [
            "assets/images/fortuner/1.jpg",
            "assets/images/fortuner/2.jpg",
            "assets/images/fortuner/3.jpg",
            "assets/images/fortuner/4.jpg",
            "assets/images/fortuner/5.jpg"
        ],
        source_link: "https://www.toyotabharat.com/showroom/fortuner/",
        featured: true
    },
    {
        id: 6,
        brand: "Honda",
        model: "City",
        year: 2024,
        variant: "ZX CVT",
        price: 1630000,
        formatted_price: "₹16,30,000",
        emi: "₹32,500",
        fuel_type: "Petrol",
        transmission: "Automatic",
        mileage: "18.4 kmpl",
        engine: "1498 cc",
        seating_capacity: "5 Seater",
        body_type: "Sedan",
        images: [
            "assets/images/city/1.jpg",
            "assets/images/city/2.jpg",
            "assets/images/city/3.jpg",
            "assets/images/city/4.jpg",
            "assets/images/city/5.jpg"
        ],
        source_link: "https://www.hondacarindia.com/honda-city",
        featured: false
    },
    {
        id: 7,
        brand: "Kia",
        model: "Seltos",
        year: 2024,
        variant: "X-Line 1.5 Diesel AT",
        price: 2034000,
        formatted_price: "₹20,34,000",
        emi: "₹39,000",
        fuel_type: "Diesel",
        transmission: "Automatic",
        mileage: "19.1 kmpl",
        engine: "1493 cc",
        seating_capacity: "5 Seater",
        body_type: "SUV",
        images: [
            "assets/images/seltos/1.jpg",
            "assets/images/seltos/2.jpg",
            "assets/images/seltos/3.jpg",
            "assets/images/seltos/4.jpg",
            "assets/images/seltos/5.jpg"
        ],
        source_link: "https://www.kia.com/in/our-vehicles/seltos/showroom.html",
        featured: false
    },
    {
        id: 8,
        brand: "MG",
        model: "Hector",
        year: 2024,
        variant: "Savvy Pro 1.5 Turbo CVT",
        price: 2214000,
        formatted_price: "₹22,14,000",
        emi: "₹42,000",
        fuel_type: "Petrol",
        transmission: "Automatic",
        mileage: "13.79 kmpl",
        engine: "1451 cc",
        seating_capacity: "5 Seater",
        body_type: "SUV",
        images: [
            "assets/images/hector/1.png",
            "assets/images/hector/2.png",
            "assets/images/hector/3.png",
            "assets/images/hector/4.png",
            "assets/images/hector/5.png"
        ],
        source_link: "https://www.mgmotor.co.in/vehicles/mghector",
        featured: false
    },
    {
        id: 9,
        brand: "Skoda",
        model: "Slavia",
        year: 2024,
        variant: "Style 1.5 TSI DSG",
        price: 1891000,
        formatted_price: "₹18,91,000",
        emi: "₹36,500",
        fuel_type: "Petrol",
        transmission: "Automatic",
        mileage: "18.41 kmpl",
        engine: "1498 cc",
        seating_capacity: "5 Seater",
        body_type: "Sedan",
        images: [
            "assets/images/slavia/1.png",
            "assets/images/slavia/2.jpg",
            "assets/images/slavia/3.png",
            "assets/images/slavia/4.jpg",
            "assets/images/slavia/5.png"
        ],
        source_link: "https://www.skoda-auto.co.in/models/slavia/slavia",
        featured: false
    },
    {
        id: 10,
        brand: "Volkswagen",
        model: "Virtus",
        year: 2024,
        variant: "GT Plus 1.5 TSI DSG",
        price: 1940000,
        formatted_price: "₹19,40,000",
        emi: "₹37,500",
        fuel_type: "Petrol",
        transmission: "Automatic",
        mileage: "18.67 kmpl",
        engine: "1498 cc",
        seating_capacity: "5 Seater",
        body_type: "Sedan",
        images: [
            "assets/images/virtus/1.png",
            "assets/images/virtus/2.jpg",
            "assets/images/virtus/3.png",
            "assets/images/virtus/4.png",
            "assets/images/virtus/5.jpg"
        ],
        source_link: "https://www.volkswagen.co.in/en/models/virtus.html",
        featured: true
    },
    {
        id: 11,
        brand: "BMW",
        model: "3 Series Gran Limousine",
        year: 2024,
        variant: "330Li M Sport",
        price: 6060000,
        formatted_price: "₹60,60,000",
        emi: "₹1,15,000",
        fuel_type: "Petrol",
        transmission: "Automatic",
        mileage: "15.39 kmpl",
        engine: "1998 cc",
        seating_capacity: "5 Seater",
        body_type: "Sedan",
        images: [
            "https://upload.wikimedia.org/wikipedia/commons/2/29/BMW_3_Series_%28G20%29.jpg",
            "assets/images/3_series_gran_limousine/2.jpg",
            "assets/images/3_series_gran_limousine/3.jpg",
            "assets/images/3_series_gran_limousine/4.jpg",
            "assets/images/3_series_gran_limousine/5.jpg"
        ],
        source_link: "https://www.bmw.in/en/all-models/3-series/gran-limousine/2022/bmw-3-series-gran-limousine-highlights.html",
        featured: false
    },
    {
        id: 12,
        brand: "Audi",
        model: "A4",
        year: 2024,
        variant: "Technology 40 TFSI",
        price: 5350000,
        formatted_price: "₹53,50,000",
        emi: "₹99,000",
        fuel_type: "Petrol",
        transmission: "Automatic",
        mileage: "17.4 kmpl",
        engine: "1984 cc",
        seating_capacity: "5 Seater",
        body_type: "Sedan",
        images: [
            "assets/images/a4/1.png",
            "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/2020_Audi_A4_35_TFSI_S_Line.jpg/800px-2020_Audi_A4_35_TFSI_S_Line.jpg",
            "https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/2020_Audi_A4_35_TFSI_S_Line_rear.jpg/800px-2020_Audi_A4_35_TFSI_S_Line_rear.jpg",
            "https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/2020_Audi_A4_35_TFSI_S_Line_interior.jpg/800px-2020_Audi_A4_35_TFSI_S_Line_interior.jpg",
            "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/2020_Audi_A4_35_TFSI_S_Line_front.jpg/800px-2020_Audi_A4_35_TFSI_S_Line_front.jpg"
        ],
        source_link: "https://www.audi.in/in/web/en/models/a4/a4-sedan.html",
        featured: false
    },
    {
        id: 13,
        brand: "Mercedes-Benz",
        model: "C-Class",
        year: 2024,
        variant: "C 220d",
        price: 6115000,
        formatted_price: "₹61,15,000",
        emi: "₹1,18,000",
        fuel_type: "Diesel",
        transmission: "Automatic",
        mileage: "23.0 kmpl",
        engine: "1993 cc",
        seating_capacity: "5 Seater",
        body_type: "Sedan",
        images: [
            "assets/images/c-class/1.png",
            "https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Mercedes-Benz_W206_113.jpg/800px-Mercedes-Benz_W206_113.jpg",
            "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Mercedes-Benz_W206_114.jpg/800px-Mercedes-Benz_W206_114.jpg",
            "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Mercedes-Benz_W206_115.jpg/800px-Mercedes-Benz_W206_115.jpg",
            "https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Mercedes-Benz_W206_116.jpg/800px-Mercedes-Benz_W206_116.jpg"
        ],
        source_link: "https://www.mercedes-benz.co.in/passengercars/models/saloon/c-class/overview.html",
        featured: true
    }
];
